qa('o que e uma rede de computadores', 'Uma rede de computadores é um aglomerado de sistemas computacionais que transmitem dados entre si. Tais sistemas podem ser computadores pessoais, celulares, impressoras, roteadores, modens, servidores, TVs, etc.').
qa('quais sao as classificacoes de redes', 'As redes são classificadas em: LAN (Local Area Network), MAN (Metropolitan Area Network), WAN (Wide Area Network).').
qa('o que e um roteador', 'Um roteador é um elemento utilizado para encaminhar pacotes de informações ao destino adequado. Para tanto, os roteadores abrem os pacotes IP e analisam cada endereço de destino, verificando a melhor rota para enviar o pacote ao destino final. Os pacotes IP levam os endereços de origem e destino. Através desses endereços, os pacotes são enviados até o seu destino.').
qa('o que e uma placa de rede', 'Uma placa de rede é um elemento empregado como interface entre o computador e o cabeamento da rede, conhecido também como adaptador. Possui um processador especializado em rotinas de armazenamento dentro da memória de leituras par a transmitir e receber dados.').
qa('o que e um modem', 'Um modem é um elemento utilizado para modular o sinal digital para que possa ser transmitido. Ou seja, transforma os sinais elétricos digitais, que saem do computador, em um formato adequado ao meio de transmissão para que, através da aplicação de técnicas que permitam a preservação da integridade dos sinais, possam ser transmitidos para longas distâncias por meio da linha telefônica.').
qa('o que e um repetidor', 'Um repetidor é um elemento empregado para a interligação de duas ou mais redes idênticas, transformando-as em uma única rede lógica. Atuando em nível físico, os repetidores simplesmente recebem os pacotes de cada uma das redes e o transmitem, sem realizar qualquer tipo de tratamento dos pacotes que por ali passam.').
qa('o que e um switch', 'Um switch é um elemento utilizado para interligar computadores e redes a fim de concentrar o cabeamento e permitir a conexão de redes de tipos diferentes.').
qa('o que e uma lan', 'Local Area Network (LAN) - corresponde a redes locais. Se restringem a uma pequena área. ').
qa('o que e man', 'Metropolitan Area Network (MAN) - corresponde a redes de alcance metropolitano. Interconecta recursos computacionais em uma área referente a uma metrópole.').
qa('o que e wan', 'Wide Area Network (WAN) - rede que interconecta recursos computacionais distantes geograficamente uns dos outros. Possui alcance intercontinental.').
qa('o que e internet', 'A internet pode ser definida como uma gigantesca rede mundial de computadores, os quais interligados por linhas comuns de telefone, linhas privadas de comunicação, cabos submarinos, canais de satélite e inúmeros outros meios de telecomunicação.').
qa('o que e correio eletronico', 'O correio eletrônico é um dos primeiros serviços disponíveis para a comunicação em rede. O correio eletrônico permite que usuários enviem e recebam mensagens eletrônicas, usando um endereço eletrônico como referência para a localização dos destinatários da mensagem.').
qa('o que e um cabo coaxial', 'O cabo coaxial é um tipo de cabo usado para transmitir sinais. Atualmente, o cabo coaxial não é mais empregado na implementação de redes, pois não é muito flexível e muitos problemas já foram detectados na utilização desse tipo de meio. Ademais, foi o primeiro cabo a ser utilizado em redes de computadores.').
qa('o que e um cabo de par trancado', 'O cabo de par trançado é o mais usado em redes. Flexível e garante uma velocidade na troca das informações compatível com as interfaces de redes. Tem nós de tamanhos distintos, melhorando a quantidade de ruídos.').
qa('o que e a fibra optica', 'Fibra óptica é um filamento flexível e transparente fabricado a partir de vidro ou plástico. A fibra óptica tem capacidade de transmitir grande volume de informações. Tal característica a torna um meio interessante para ser implementada em locais com essas possibilidades.').
qa('o que e radiofrequencia', 'A radiofrequência é o meio não físico utilizado para transmitir informações. A este tipo de meio convencionou-se chamar de wireless e as tecnologias mais conhecidas que desse se utilizam são o telefone celular, WI-FI, WiMAX, satélite, infravermelho e Bluetooth.').
qa('o que sao topologias de redes', 'A topologia, em redes de computadores, está relacionada à forma como as interfaces são conectadas umas às outras. Essa característica define o seu tipo, a eficiência da rede e sua velocidade.').
qa('o que e uma topologia parcialmente ligada', 'Nesta topologia, os computadores são interligados de forma intermediária, ou seja, não são todos os computadores que são interligados.').
qa('o que e uma topologia em barramento', 'Este tipo de topologia consiste em ter um meio de comunicação comum, ou seja, todos os computadores são conectados a esse meio para estabelecer comunicação entre si. Os computadores são conectados ao meio por uma interface cuja responsabilidade é detectar os sinais transmitidos pelos computadores e tratá-los para que sejam devidamente entendidos pela máquina destinatária.').
qa('o que e uma topologia ponto a ponto', 'Este tipo de topologia caracteriza-se por enviar os dados apenas em um sentido como, por exemplo, sentido anti-horário. Dessa forma, os dados transmitidos deverão passar pelos computadores até alcançarem o seu destino.').
qa('o que e uma topologia multiponto', 'Este tipo de topologia é também conhecido como token ring. Caracteriza-se por circular no anel, um conjunto padrão de oito bits, chamado de token. Quando uma das máquinas tiver que transmitir alguma informação, deverá capturar esse token e transmitir os dados. Após a transmissão dos dados, a máquina deverá inserir o token novamente no anel. Tal mecanismo é executado para que não haja colisão dos dados a serem transmitidos, pois só poderá transmitir os dados a máquina que conseguir capturar o token; aquela que não conseguir, deverá esperar.').
qa('o que e uma topologia em estrela', 'Caracteriza-se por ter um ponto central para interligar os computadores a fim de estabelecer comunicações. O ponto central age como centro de controle da rede, interligando todas as máquinas.').
qa('fim', 'Até a próxima!').