qa('o que e ethernet', 'A ethernet constitui um conjunto de protocolos e técnicas para tornar viável a comunicação entre os computadores. É usada na grande maioria das redes de computadores LAN instaladas pelo mundo. Muitas vezes, o termo ethernet é empregado para definir as redes locais.').
qa('o que e enderecamento na ethernet e quais sao os seus servicos', 'A  ethernet oferece a comunicação entre equipamentos de uma mesma rede física sem o uso de conexões e com serviços: unicast, multicast e broadcast. Para concretizar esses serviços, cada componente de rede participante da comunicação possui um endereço único, chamado de endereço MAC, ou endereço físico.').
qa('o que e um protocolo mac', 'Conceitualmente, uma rede ethernet simples consiste em um barramento único que todas as máquinas querem acessar para realizar suas transmissões de dados. Como esse meio é compartilhado, há a necessidade de controlar o acesso ao meio, de modo que cada estação possa transmitir um quadro de cada vez. O Media Access Control (MAC) é responsável por esse controle.').
qa('o que e padrao gigabit ethernet', 'O Padrão Gigiabit Ethernet é um meio físico de transmissão de uma rede LAN na velocidade de 1 Gigabit por segundo.').
qa('o que e metro ethernet', 'Metro ethernet é uma tecnologia que permite utilizar redes ethernet em áreas metropolitanas e geograficamente distribuídas.').
qa('o que e o protocolo tcp/ip', 'O protocolo TCP/IP é constituído por outros protocolos e cada um tem uma função específica dentro da suíte TCP/IP. Foi dividido em camadas para se tornar compatível ao modelo de referência OSI. O TCP/IP foi criado antes da padronização do modelo de referência OSI. Esse modelo foi estabelecido para poder padronizar as funções e características dos protocolos a serem desenvolvidos.').
qa('quais sao os protocolos que constituem o tcp', 'Aplicação, Apresentação, Sessão, Transporte, Redes, Enlace e Física.').
qa('o que e rip', 'O Protocolo de Informações sobre Rotas (RIP) foi um dos primeiros protocolos de roteamento dinâmico. Usa um algoritmo de vetor de distância que determina a melhor rota através de uma métrica de pulos. É um protocolo eficiente quando usado em pequenas redes, pois este foi o objetivo quando da criação desse protocolo. Nessa época, não se imaginava que a internet teria um crescimento significativo, como ocorre atualmente.').
qa('o que e igrp', 'Este protocolo é proprietário da Cisco. Foi projetado com o objetivo de trazer melhorias para o protocolo RIP. Conforme a rede foi crescendo, o protocolo RIP passou a ficar limitado, de modo que o protocolo IGRP solucionou alguns problemas relacionados a rotas em redes grandes e heterogêneas.').
qa('o que e eigrp', 'É outro protocolo desenvolvido pela Cisco. É considerado um protocolo híbrido combinando as melhores características dos protocolos para a definição de rotas com base em vetores de distância e em estado de ligação. Por exemplo, usa mensagens de notificação para obter informações sobre roteadores vizinhos. Utiliza também um protocolo especialmente projetado, o protocolo de transporte confiável para transmitir as atualizações sobre rotas.').
qa('o que e smtp', 'O Simple Mail Transfer Protocol (SMTP) corresponde a um dos serviços prestados pela camada de aplicação. Os componentes básicos envolvidos na troca de mensagens através do SMTP são: Agente usuário e Caixa postal. O SMTP utiliza os serviços da camada de transporte através do protocolo TCP para transferir mensagens. Apresenta uma estrutura organizada para a transmissão dos dados.').
qa('o que e telnet', 'É um protocolo para acesso remoto utilizado para configurações de máquinas. Fornece um serviço de terminal virtual. Uma vez estabelecida uma sessão de login remoto, Telnet disponibiliza mecanismos necessários para que os caracteres digitados na máquina local sejam passados diretamente à máquina remota. Não há interface gráfica; tudo é feito na linha de comando. Usa o protocolo TCP para o transporte confiável dos dados e é acessível através de programas de aplicação, chamados, na maioria das vezes, Telnet. Com este tipo de protocolo, os administradores de rede podem acessar, de forma remota, os roteadores ou outros dispositivos de rede que estão geograficamente distantes e implantados sobre o seu domínio.').
qa('o que e ftp', 'É um protocolo de transferência de arquivos entre dois sistemas que utiliza duas conexões: uma é empregada para dar suporte ao processo de transferência de dados e a outra conexão é utilizada para dar suporte aos vários processos de controle da sessão.').
qa('o que e http', 'O protocolo de transferência e hipertexto é o protocolo em que a world wide web está baseada. É considerado um protocolo de pedido e resposta e funciona da seguinte forma: um programa cliente estabelece uma conexão TCP com um programa servidor HTTP. O programa servidor aceita essa conexão e responde ao pedido do cliente. As mensagens de pedido são feitas por meio de um agente usuário, que conhecemos como browser. As mensagens de respostas são fornecidas pelo servidor após receber e interpretar a mensagem de pedido. As mensagens têm uma linha de início, um campo cabeçalho, uma linha em branco que significa o final do cabeçalho e um corpo de mensagem que contém o retorno da solicitação.').
qa('o que e camada de rede', 'A camada de rede lida com as transferências de pacotes de uma origem para um destino. O objetivo básico da camada de rede é fornecer os serviços de transferência de dados fim a fim sobre uma rede, independentemente das características das subredes físicas. Está mais relacionada à topologia de rede e tem como uma de suas principais funções resolver problemas de roteamento em rede.').
qa('o que e ipv4', 'IPv4 é o protocolo largamente usado para troca de dados atualmente. É o formato de endereço padrão que permite que todos os computadores na internet se comuniquem entre si. O IPv4 é escrito como uma sequência de dígitos de 32 bits e um endereço IPv4 é composto por quatro números, cada um entre 0 e 255, separados por pontos.').
qa('o que e icmp', 'O Internet Control Message Protocol (ICMP) é um protocolo da camada 3, usado para trocar mensagens entre equipamentos que estão interligados na rede. Em redes LAN, é empregado, pelos administradores de rede, para verificar se um determinado equipamento está devidamente conectado à rede.').
qa('fim', 'Até a próxima!').